name: Cypress Tests
on:
  push:
    branches:
      - main
#on:
#schedule:
#- cron: '30 11 * * *' # Runs at 14:30 UTC+3 every day

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npm run cypress:run
      - name: Generate multi-html-report
        run: node reporter.js
      - name: Genarete the Test Coverage file
        run: node testCoverage.js
      - name: Save reports folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          if-no-files-found: error
          path: reports
