name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [18.x]

   steps:
     - uses: actions/checkout@v3
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
        node-version: ${{ matrix.node-version }}
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run --browser chrome
     - name: Save reports folder
       uses: actions/upload-artifact@v3
       with:
         name: reports
         if-no-files-found: error
         path: reports/html
